# Generated by Django 6.0.6 on 2026-06-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Patrocinador')),
                ('logo', models.ImageField(upload_to='logos_patrocinadores/', verbose_name='Logotipo')),
                ('site_url', models.URLField(blank=True, null=True, verbose_name='Site do Patrocinador')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
            ],
        ),
    ]
