# Generated by Django 6.0.6 on 2026-06-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Publicação')),
                ('imagem', models.ImageField(upload_to='blog_fotos/', verbose_name='Imagem de Destaque')),
                ('texto_descritivo_imagem', models.CharField(max_length=255, verbose_name='Texto Alternativo (Acessibilidade/SEO)')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Publicação')),
            ],
        ),
    ]
