# Generated by Django 6.0.6 on 2026-06-26 21:47

import apps.institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('instagram', models.CharField(help_text='Apenas o @perfil (Ex: hugelmannerplattler)', max_length=50, verbose_name='Instagram')),
                ('no_grupo_desde', models.CharField(help_text='Ex: Julho de 2015', max_length=50, verbose_name='No grupo desde')),
                ('foto', models.ImageField(upload_to=apps.institucional.models.caminho_foto_integrante, verbose_name='Foto do Integrante')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'ordering': ['nome'],
            },
        ),
    ]
