# Generated by Django 6.0.6 on 2026-06-26 22:12

import apps.institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Evento')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, help_text='Preencha apenas se o evento durar mais de um dia', null=True, verbose_name='Data de Término')),
                ('horario', models.CharField(help_text='Ex: 19:30h ou Durante o dia', max_length=50, verbose_name='Horário')),
                ('local', models.CharField(help_text='Ex: Praça Central', max_length=150, verbose_name='Local da Apresentação')),
                ('cidade', models.CharField(help_text='Ex: Domingos Martins - ES', max_length=100, verbose_name='Cidade / Estado')),
                ('descricao', models.TextField(blank=True, verbose_name='Breve Descrição do Evento')),
                ('card_divulgacao', models.ImageField(blank=True, null=True, upload_to=apps.institucional.models.caminho_card_agenda, verbose_name='Card de Divulgação (Imagem)')),
                ('link_ingresso', models.URLField(blank=True, help_text='Link para compra ou mais informações (se houver)', null=True, verbose_name='Link Externo / Ingresso')),
            ],
            options={
                'verbose_name': 'Evento da Agenda',
                'verbose_name_plural': 'Eventos da Agenda',
                'ordering': ['data_inicio'],
            },
        ),
    ]
