# Generated by Django 6.0.6 on 2026-07-27 17:04

import apps.institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Produto')),
                ('descricao', models.TextField(verbose_name='Descrição do Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('imagem', models.ImageField(upload_to=apps.institucional.models.caminho_foto_produto, verbose_name='Foto do Produto')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível para Venda')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
