# Generated by Django 6.0.6 on 2026-08-06 21:11

import apps.institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0003_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Parceiro / Apoiador')),
                ('logo', models.ImageField(upload_to=apps.institucional.models.caminho_logo_parceiro, verbose_name='Logo / Marca')),
                ('site_url', models.URLField(blank=True, help_text='Link para o site do parceiro (opcional)', null=True, verbose_name='Link Externo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Exibir no site')),
                ('ordem', models.IntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Parceiro / Apoiador',
                'verbose_name_plural': 'Parceiros e Apoiadores',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
