# Generated by Django 6.0.6 on 2026-08-07 13:18

import apps.institucional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0004_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título / Legenda')),
                ('imagem', models.ImageField(upload_to=apps.institucional.models.caminho_foto_galeria, verbose_name='Foto')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Galeria de Fotos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
