# Generated by Django 6.0.6 on 2026-06-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('data', models.DateField(verbose_name='Data do Evento')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('local', models.CharField(max_length=255, verbose_name='Local/Cidade')),
                ('link_ingresso', models.URLField(blank=True, null=True, verbose_name='Link para Informações/Ingresso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição Breve')),
            ],
        ),
    ]
